// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHgIH1mUJUpwSgq90rnzfNl5reBKvyvMk',
    appId: '1:917019747278:android:b0cf68395963f935f4c19f',
    messagingSenderId: '917019747278',
    projectId: 'green-track-729ca',
    storageBucket: 'green-track-729ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHgIH1mUJUpwSgq90rnzfNl5reBKvyvMk',
    appId: '1:917019747278:android:b0cf68395963f935f4c19f',
    messagingSenderId: '917019747278',
    projectId: 'green-track-729ca',
    storageBucket: 'green-track-729ca.appspot.com',
    //androidClientId: '252065178893-gqc3s34jjr899jjgbhdevgq0ksl3b8cc.apps.googleusercontent.com',
    //iosClientId: '252065178893-05vp03un6r01ou45ad80opjvn3kv7666.apps.googleusercontent.com',
    //: 'com.dis.malia',
  );
}
